### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [jan-auer/zsh-multiline#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by jan-auer** [comment]
Awesome! Added a preview animation to the readme (which for some reason turned out pretty bad-quality). If you prefer a static image, use this please: 

![zsh-multiline](https://user-images.githubusercontent.com/1433023/33217324-bd07ccb8-d137-11e7-9423-375c770d0cda.png)

**Comment by jan-auer** [comment]
Updated the preview with a higher quality animation...
